[config]
schemaVersion = "0.0.1"

[package]
namespace = "funlennysub"
name = "UpgradeSolver"
description = "Upgrade placement solver"
websiteUrl = "https://github.com/funlennysub/UpgradeSolver"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack_Mycopunk = "5.4.2403"

[build]
icon = "icon.png"
readme = "README.md"
outdir = "build"

[[build.copy]]
source = "bin/Release/net48/UpgradeSolver.dll"
target = "BepInEx/plugins/UpgradeSolver.dll"

[[build.copy]]
source = "CHANGELOG.md"
target = "CHANGELOG.md"

[[build.copy]]
source = "LICENSE"
target = "LICENSE"

[publish]
repository = "https://thunderstore.io"
communities = ["mycopunk"]

[publish.categories]
mycopunk = ["qol", "client"]
